### ISSUE TITLE
Написать оформленное ТЗ

### ISSUE THREAD

**Issue by TorturedDude** [TorturedDude/KWMusicPleer#2]

**Comment by TorturedDude** [comment]
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1. ТЕХНИЧЕСКОЕ ЗАДАНИЕ<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.1. Общие сведения<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.1.1. Полное наименование системы<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Веб-приложение для поиска и прослушивания музыкальных композиций.<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.1.2. Плановые сроки начала и окончания работы по созданию системы<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Начало работы: 01.09.2021<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Окончание работы: 01.12.2021<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.2. Назначение и цели создания (развития) системы<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.2.1. Назначение системы<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Назначением системы является автоматизация поиска и прослушивания музыкальных композиций с помощью веб-приложения с использованием базы данных.<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.2.2. Цели создания системы<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Цель создания системы – получить прибыль за счет предоставления платных подписок на музыкальные композиции.<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.3. Характеристики объекта автоматизации<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Объектом автоматизации является музыкальный плеер. Автоматизированию подлежит демонстрация, поиск и прослушивание имеющихся музыкальных альбомов и композиций.<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.4. Требования к системе<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.4.1. Требования к системе в целом<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Программный продукт должен представлять собой веб-приложение.<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.4.2. Требования к структуре и функционированию системы<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Приложение должно быть разделено на 3 слоя:<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">- Слой клиентского приложения в виде веб-страницы;<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">- Слой бизнес-логики приложения (сервер);<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">- Слой хранения данных (база данных).<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Функционал приложения должен содержать:<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 4.8px 0.0px; font: 14.0px 'Times New Roman'">• Авторизацию пользователей;<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 4.8px 0.0px; font: 14.0px 'Times New Roman'">• Поиск музыкальных композиций и альбомов;<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 4.8px 0.0px; font: 14.0px 'Times New Roman'">• Хранение пользовательских плейлистов и списков альбомов;<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 4.8px 0.0px; font: 14.0px 'Times New Roman'">• Воспроизведение музыкальных композиций;<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 4.8px 0.0px; font: 14.0px 'Times New Roman'">• Создание недельных чартов, основанных на количестве прослушиваний музыкальных композиций за текущую неделю;<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">• Хранение недельных чартов предыдущих недель.<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'; min-height: 16.0px"><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.4.3. Требования к надежности<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Система должна обеспечивать корректную обработку исключительных ситуаций, вызванных, например, вводом неверных пользовательских данных или неоднозначной информации в базу данных.<span class="Apple-converted-space">&nbsp;</span></p>


**1.5. Состав и содержание работ по созданию системы**
Стадии | Этапы работ | Сроки исполнения
|----:|:----:|:----------|
|1. Формирование требований к АС | 1.1. Исследование объекта и подтверждение необходимости создания АС.  1.2. Формирование требований пользователя к АС.  1.3. Оформление отчёта о  выполненной работе и заявки на разработку АС. | 
|2. Разработка концепции АС. | 2.1. Изучение выбранного объекта.  2.2. Проведение научно- исследовательских работ.  2.3. Проектирования концепции АС, удовлетворяющей потребности пользователя.  2.4. Оформление отчёта о выполненной работе. |
|3. Техническое задание. | Разработка и утверждение технического задания на создание АС. |
|4. Разработка системы. | Разработка системы согласно  техническому заданию. |
|5. Защита курсовой работы. | 5.1. Создание грамотной презентации и речи для защиты курсовой работы. 5.2  Защита курсовой работы. |

<br class="Apple-interchange-newline">

**1.6. Порядок контроля и приемки системы
1.6.1. Состав, объем и методы испытаний системы и ее составных частей**
Приложение должно пройти предварительные испытания, состоящие из отладки и минимального набора тестов.
В результате предварительных испытаний, должны быть исправлены недочеты, замечания на которые были получены в ходе предварительных испытаний.
Для проверки корректной работы внесённых изменений должны быть проведены повторные испытания разработанной системы.
**1.6.2. Общие требования к приемке работ**
В процессе приемки работ должна быть осуществлена проверка на соответствие требованиям настоящего «Технического задания». По результатам испытаний возможны доработки и исправления.
9
**1.7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие**
При подготовке объекта автоматизации к вводу системы в действие следует выполнить:
• Обеспечение работ по вводу данных в систему;
• Развертывание системы на сервере;
• Настройка системы доступа и создание учетных записей.
**1.8. Требования к документированию**
По окончанию работы предъявлена расчетно-пояснительная записка, в состав которой входят:
• Техническое задание;
• Научно-исследовательская часть;
• Проектно-конструкторская часть;
• Проектно-технологическая часть.
Также должна быть предоставлена графическая часть работы, выполненная в формате А1 на 2 листах, в которую входят:
• Демонстрационные чертежи;
• Алгоритмические схемы.
**1.9. Источники разработки**
• Гост 34.601-90;
• Гост 34.602-89.

**Comment by wldmr-key** [comment]
Неплохо, но есть вопросы по существу. Функции не соответствуют цели - нет функции подписки. Откуда на сайте берутся композиции? Оплачивается ли роялти за их прослушивание/возможность предоставления?

**Comment by TorturedDude** [comment]
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1. ТЕХНИЧЕСКОЕ ЗАДАНИЕ<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.1. Общие сведения<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.1.1. Полное наименование системы<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Веб-приложение для поиска и прослушивания музыкальных композиций.<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.1.2. Плановые сроки начала и окончания работы по созданию системы<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Начало работы: 01.09.2021<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Окончание работы: 01.12.2021<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.2. Назначение и цели создания (развития) системы<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.2.1. Назначение системы<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Назначением системы является автоматизация поиска и прослушивания музыкальных композиций с помощью веб-приложения с использованием базы данных.<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.2.2. Цели создания системы<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Цель создания системы – получить прибыль за счет предоставления платных подписок на музыкальные композиции.<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.3. Характеристики объекта автоматизации<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Объектом автоматизации является музыкальный плеер. Автоматизированию подлежит демонстрация, поиск и прослушивание имеющихся музыкальных альбомов и композиций.<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.4. Требования к системе<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.4.1. Требования к системе в целом<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Программный продукт должен представлять собой веб-приложение.<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.4.2. Требования к структуре и функционированию системы<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Приложение должно быть разделено на 3 слоя:<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">- Слой клиентского приложения в виде веб-страницы;<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">- Слой бизнес-логики приложения (сервер);<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">- Слой хранения данных (база данных).<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Функционал приложения должен содержать:<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 4.8px 0.0px; font: 14.0px 'Times New Roman'">• Авторизацию пользователей;<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 4.8px 0.0px; font: 14.0px 'Times New Roman'">• Поиск музыкальных композиций и альбомов;<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 4.8px 0.0px; font: 14.0px 'Times New Roman'">• Хранение пользовательских плейлистов и списков альбомов;<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 4.8px 0.0px; font: 14.0px 'Times New Roman'">• Воспроизведение музыкальных композиций;<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 4.8px 0.0px; font: 14.0px 'Times New Roman'">• Создание недельных чартов, основанных на количестве прослушиваний музыкальных композиций за текущую неделю;<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">• Хранение недельных чартов предыдущих недель;<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">• Возможность оформления платной подписки;<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">• Оплата авторам, музыкальных композиций, за определенное кол-во прослушиваний на их композициях.<span class="Apple-converted-space">&nbsp;</span></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'; min-height: 16.0px"><br></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'"><b>1.4.3. Требования к надежности<span class="Apple-converted-space">&nbsp;</span></b></p>
<p style="margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px 'Times New Roman'">Система должна обеспечивать корректную обработку исключительных ситуаций, вызванных, например, вводом неверных пользовательских данных или неоднозначной информации в базу данных.<span class="Apple-converted-space">&nbsp;</span></p>


**1.5. Состав и содержание работ по созданию системы**
Стадии | Этапы работ | Сроки исполнения
|----:|:----:|:----------|
|1. Формирование требований к АС | 1.1. Исследование объекта и подтверждение необходимости создания АС.  1.2. Формирование требований пользователя к АС.  1.3. Оформление отчёта о  выполненной работе и заявки на разработку АС. | 
|2. Разработка концепции АС. | 2.1. Изучение выбранного объекта.  2.2. Проведение научно- исследовательских работ.  2.3. Проектирования концепции АС, удовлетворяющей потребности пользователя.  2.4. Оформление отчёта о выполненной работе. |
|3. Техническое задание. | Разработка и утверждение технического задания на создание АС. |
|4. Разработка системы. | Разработка системы согласно  техническому заданию. |
|5. Защита курсовой работы. | 5.1. Создание грамотной презентации и речи для защиты курсовой работы. 5.2  Защита курсовой работы. |

<br class="Apple-interchange-newline">

**1.6. Порядок контроля и приемки системы
1.6.1. Состав, объем и методы испытаний системы и ее составных частей**
Приложение должно пройти предварительные испытания, состоящие из отладки и минимального набора тестов.
В результате предварительных испытаний, должны быть исправлены недочеты, замечания на которые были получены в ходе предварительных испытаний.
Для проверки корректной работы внесённых изменений должны быть проведены повторные испытания разработанной системы.
**1.6.2. Общие требования к приемке работ**
В процессе приемки работ должна быть осуществлена проверка на соответствие требованиям настоящего «Технического задания». По результатам испытаний возможны доработки и исправления.
9
**1.7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие**
При подготовке объекта автоматизации к вводу системы в действие следует выполнить:
• Обеспечение работ по вводу данных в систему;
• Развертывание системы на сервере;
• Настройка системы доступа и создание учетных записей.
**1.8. Требования к документированию**
По окончанию работы предъявлена расчетно-пояснительная записка, в состав которой входят:
• Техническое задание;
• Научно-исследовательская часть;
• Проектно-конструкторская часть;
• Проектно-технологическая часть.
Также должна быть предоставлена графическая часть работы, выполненная в формате А1 на 2 листах, в которую входят:
• Демонстрационные чертежи;
• Алгоритмические схемы.
**1.9. Источники разработки**
• Гост 34.601-90;
• Гост 34.602-89.

**Comment by wldmr-key** [comment]
норм. Берем ))
