### ISSUE TITLE
Написать предварительное описание предметной области и требований к системе

### ISSUE THREAD

**Issue by TorturedDude** [TorturedDude/KWMusicPleer#3]

**Comment by TorturedDude** [comment]
**Описание предметной области**

В данном приложении существуют песни, альбомы, исполнители, подписки и недельные чарты.  

- У каждого альбома есть обложка, название, список песен, список исполнителей, список пользователей, которые добавили альбом в свою фонотеку и дата релиза; 
- Каждая песня содержит обложку, название песни, свой альбом, список исполнителей, файл песни, список пользователей, которые добавили песню в свою фонотеку, дату релиза, количество прослушиваний(всего) и количество прослушиваний в рамках недельного чарта; 
- Каждый исполнитель содержит фотографию, псевдоним и списки выпущенных альбомов и песен; 
- Подписка содержит список владельцев, стоимость.
- Недельные чарты представляют собой дату проведения чарта и список песен, вошедших в каждый из них с позиционированием. 

Благодаря внедрению панели администратора в систему облегчается взаимодействие с данными. 

Описание и функционал со стороны администратора: 

Администратор имеет доступ ко всем данным системы, а также может с легкостью добавлять, изменять, удалять их. 

Описание и функционал со стороны пользователя: 

- Отслеживание новинок недели, месяца, года; 
- Просмотр чарта как текущей недели, так и предшествующих недель; 
- Добавление альбомов и песен в личную фонотеку, для удобства (только для авторизованных пользователей); 
- Поиск по ключевым словам(названиям альбомов, песен, именам исполнителей); 
- Авторизация / регистрация в системе; 
- Оформление платной подписки;
- Прослушивание песен.

**Comment by TorturedDude** [comment]
**Описание предметной области**

В данном приложении существуют песни, альбомы, исполнители и недельные чарты.  

- У каждого альбома есть обложка, название, список песен, список исполнителей, список пользователей, которые добавили альбом в свою фонотеку и дата релиза; 
- Каждая песня содержит обложку, название песни, свой альбом, список исполнителей, файл песни, список пользователей, которые добавили песню в свою фонотеку, дату релиза, количество прослушиваний(всего) и количество прослушиваний в рамках недельного чарта; Песня может как состоять в альбоме, так и не состоять, ремикс является отдельной песней; 
- Каждый исполнитель содержит фотографию, псевдоним и списки выпущенных альбомов и песен; 
- Недельные чарты представляют собой дату проведения чарта и список песен, вошедших в каждый из них с позиционированием. 

Благодаря внедрению панели администратора в систему облегчается взаимодействие с данными. 

Описание и функционал со стороны администратора: 

Администратор имеет доступ ко всем данным системы, а также может с легкостью добавлять, изменять, удалять их. 

Описание и функционал со стороны пользователя: 

- Отслеживание новинок недели, месяца, года; 
- Просмотр чарта как текущей недели, так и предшествующих недель; 
- Добавление альбомов и песен в личную фонотеку, для удобства (только для авторизованных пользователей); 
- Поиск по ключевым словам(названиям альбомов, песен, именам исполнителей); 
- Авторизация / регистрация в системе; 
- Оформление платной подписки;
- Прослушивание песен.

**Comment by wldmr-key** [comment]
> Администратор имеет доступ ко всем данным системы, а также может с легкостью добавлять, изменять, удалять их.

прямо так? Грохнуть все, например? Или чарт подкрутить?

Нет ответа на вопрос:

> Подписка -что это такое?

**Comment by TorturedDude** [comment]
**Описание предметной области**

В данном приложении существуют песни, альбомы, исполнители, подписки и недельные чарты.  

- У каждого альбома есть обложка, название, список песен, список исполнителей, список пользователей, которые добавили альбом в свою фонотеку и дата релиза; 
- Каждая песня содержит обложку, название песни, свой альбом, список исполнителей, файл песни, список пользователей, которые добавили песню в свою фонотеку, дату релиза, количество прослушиваний(всего) и количество прослушиваний в рамках недельного чарта; Песня может как состоять в альбоме, так и не состоять, ремикс является отдельной песней;
- Каждый исполнитель содержит фотографию, псевдоним и списки выпущенных альбомов и песен; 
- Подписка содержит стоимость. Подписка определяет есть ли ограничение на прослушивание и скачивание песен.
- Недельные чарты представляют собой дату проведения чарта и список песен, вошедших в каждый из них с позиционированием. Включение песни в чарты не влияет на чарты, влияет общее количество прослушиваний за неделю на включение в чарты.

Благодаря внедрению панели администратора в систему облегчается взаимодействие с данными. 

Описание и функционал со стороны администратора: 

Администратор имеет доступ ко всем данным системы, а также может с легкостью добавлять, изменять, удалять их. Но есть и исключение, администратор не может изменять недельные чарты. 

Описание и функционал со стороны пользователя: 

- Отслеживание новинок недели, месяца, года; 
- Просмотр чарта как текущей недели, так и предшествующих недель; 
- Добавление альбомов и песен в личную фонотеку, для удобства (только для авторизованных пользователей); 
- Поиск по ключевым словам(названиям альбомов, песен, именам исполнителей); 
- Авторизация / регистрация в системе; 
- Оформление платной подписки;
- Прослушивание песен.

**Comment by wldmr-key** [comment]
так и не понял, какие ограничения для тех, у кого нет подписки?

**Comment by TorturedDude** [comment]
По-моему, я вроде достаточно понятным языком описал, что такое подписка и всё же, сейчас 21 век и все знают, для чего нужна подписка на музыку

**Comment by wldmr-key** [comment]
По-моему, я вроде достаточно понятным языком спросил, какие ограничения для тех, у кого нет подписки? Что этим бедолагам нельзя делать? Скачиать? Слушать? Картинки смотреть?
