### ISSUE TITLE
Выполнить предварительный анализ аналогов

### ISSUE THREAD

**Issue by TorturedDude** [TorturedDude/KWMusicPleer#4]

**Comment by TorturedDude** [comment]
**SoundCloud** 

Главная задача – это прослушивание музыки, плеер интегрирован в приложение. Здесь есть возможность потокового прослушивания аудиозаписей и создания плейлистов неограниченного объёма. [3] 

Главная страница SoundCloud представлена на Рисунке 2.3.1. 

![alt text](https://subme.ru/wp-content/uploads/2021/05/soundcloud-kak-zagruzit-na-pk-na-telefon-1-1024x358.jpg)

Рисунок 2.3.1 - Главная страница SoundCloud [1] 



**Функционал:** 



- Проигрывание станций – каждый пользователь сервиса может публиковать свои аудиоподборки, которые будут доступны широкой публики. Чтобы послушать композиции, достаточно кликнуть по станции. 
- Обзор – на данной странице пользователю предлагаются чарты от SoundCloud, а также фильтр композиций по жанрам. 
- Создание плейлистов – музыкальная социальная сеть позволяет формировать свои собственные плейлисты. 
- Воспроизведение похожих дорожек. 



**Плюсы:** 



- Уникальность композиций. 
- Возможность прослушивания + составления собственного альбома 
- Отображение статистики прослушиваний, просмотров. 
- Возможность комментировать альбомы и песни. 





**Минусы:**  

- Ограничение по аккаунту. 
- Ограничение количества скачиваний. 



**Spotify** 

Spotify – это сервис для стриминга различного контента (миллионов треков, подкастов и видеороликов) от авторов со всего мира. 

Основной функционал, такой как воспроизведение музыки – бесплатный. Также можно оформить Premium-подписку. [5] 

![alt text](https://cdn.lifehacker.ru/wp-content/uploads/2011/12/Snimok-ekrana-2020-07-15-v-14.02.38_1594819250-1024x512.jpeg)


Рисунок 2.3.2 – Главная страница Spotify для ПК [2] 



**Функционал:** 


- Получение рекомендаций на основе своих предпочтений. 
- Создание своих коллекций музыки и подкастов. 
- Главное преимущество – алгоритмы подбора музыки, которые практически идеально подстраиваются под вкусы слушателей. 



Сервис Spotify доступен на разных устройствах, включая компьютеры, телефоны и планшеты, а также динамики, телевизоры и автомобильные аудиосистемы. 



**Преимущества:** 


- Добавление подписчиков. 
- Создание плейлистов. 
- Наличие официального приложения для смартфона и компьютера. И основные плюсы Spotify связаны с тем, что программу можно без проблем установить на любое устройство. 
- Рекомендации. 
- Высокое качество звучания. 



**Недостатки:** 


- Большое количество ограничений в бесплатной версии.

**Comment by wldmr-key** [comment]
я бы добавил еще парочку сервисов (возможно не так развернуто) и сделал бы общие выводы о требованиях к твоему приложению.
Было бы неплохо приложить жалобы и похвалы пользователей или ссылки на независимые обзоры
А так, в общем, неплохо

**Comment by TorturedDude** [comment]
**Я решил добавить пару отзывов пользователей данных сервисов, а по поводу пары вариантов, я считаю, что этих будет достаточно.**

**Comment by TorturedDude** [comment]
**Данный отзыв был добавлен после описание такого сервиса, как spotify**

**Comment by TorturedDude** [comment]
[![La_Muchacha аватар](https://cdn-irec.r-99.com/sites/default/files/imagecache/60i/pictures/14/picture-143725-z+U6ghNM.jpg "Информация о пользователе.")](/users/lamuchacha "Информация о пользователе.")

**[La\_Muchacha](/users/lamuchacha "Информация о пользователе.")**

 

Опубликовано 24 Декабрь, 2014 - 20:26

[И как я раньше жила без этого ресурса?... Отличный музыкальный сайт, объединяющий меломанов во всем мире! Инструкция по применению, много букв и скринов.](/content/i-kak-ya-ranshe-zhila-bez-etogo-resursa-otlichnyi-muzykalnyi-sait-i-udobnoe-prilozhenie-dlya)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

_**Здравствуйте, дорогие читатели!**_

Хлебом меня не корми, дай со всеми поделиться находками на просторах глобальной сети! На сей раз расскажу про сайт, который буквально собирает саундтреки к моей жизни. Хорошая музыка способна скрасить рабочие будни и домашние дела, и в этом мне помогает ресурс **[Soundcloud](/external_redirect?extUrl=3vUCACadFXoSJQwpfLqpZt9O7RczYoFOgbHobfxe5I81mOIRZUMH3sJF%252BfmnHtiNef6DWZIzNaBHbqTuMGyoWMPBpk8zMRhHW2eSdtnwX042M9VEzksVF9f2v6Ck6e1aOAWqyClIn2pb4A%253D%253D&km=1)**, также есть одноименное мобильное приложение!

**Вот так, собственно, выглядит моя страничка в профиле!**

**![](https://cdn-irec.r-99.com/sites/default/files/imagecache/copyright/user-images/143725/KwQm1WpLUwjk8lbrcwiw.jpg)
**

До встречи с Soundcloud мой музыкальный плейлист состоял исключительно из рок-музыки и всех её производных. Электронные направления я принципиально игнорировала, ибо то, что массово звучит из всех телевизоров, радиоприемников, утюгов либо не радовало совсем, либо быстро приедалось.

Совершенно случайно, копаясь в бесплатных предложениях на App Store, наткнулась на виновника данного отзыва. Просто для пробы загрузила приложение. Надо сказать, что пользоваться им на мобильном устройстве немного более хлопотно, чем на компе. Поэтому решила посмотреть сайт.

**Конечно, можно наслаждаться музыкой и без регистрации, но лучше все же залогиниться, ибо открывается много возможностей!**

_Процедура регистрации на Soundcloud проще пареной репы!_

![](https://cdn-irec.r-99.com/sites/default/files/imagecache/copyright/user-images/143725/7q9HDvZSAziMaq0hWbCGA.jpg)

А у тебя есть профиль на SOUNDCLOUD???

![](https://cdn-irec.r-99.com/sites/default/files/imagecache/copyright/user-images/143725/6vx8g7UL55zN7uOcP3bCA.jpg)

Все как везде!

_Можно зайти на soundcloud через профили в Фейсбуке или Гугл Хром. Но я все же создала отдельный профиль!_

**После регистрации Вы попадаете в большой музыкальный поток, аж глаза разбегаются, что послушать!**

![](https://cdn-irec.r-99.com/sites/default/files/imagecache/copyright/user-images/143725/iTVzbRBuPBq8uniljrAQng.jpg)

Для начала выбираем стиль, который Вы предпочитаете! Здесь найдутся треки для всех слоев населения - и для рокеров, и для поклонников жанра регги и афробит, и для любителей танцевальной и электронной музыки!

![](https://cdn-irec.r-99.com/sites/default/files/imagecache/copyright/user-images/143725/2H5cltEl7Mx6l8n0DiH9Wg.jpg)

Допустим, душа просит послушать Инди-рок. И программа выдает треки, загруженные на ресурс, в этом направлении. Советую первым делом слушать треки с наибольшим числом комментариев и отзывов! Логично, если песня набрала много откликов, значит, она априори должна быть классной! Но бывает и так, что натыкаешься на улетный трек, а он и без комментариев совсем...

![](https://cdn-irec.r-99.com/sites/default/files/imagecache/copyright/user-images/143725/2KOhNbAy5nXXh9NyIJxXKQ.jpg)

Также работает поиск по хэш-тегам. В качестве хэш-тега можно задать музыкальный стиль, имя исполнителя, название группы, тематику треков и искать по ним дорожки либо плейлисты.

![](https://cdn-irec.r-99.com/sites/default/files/imagecache/copyright/user-images/143725/Df0UHZoap5B5OnTdnN7xg.jpg)

**Зарегистрированный пользователь тоже может оставлять комментарии к любому понравившемуся треку! При этом Вы можете комментировать песню на любом моменте звучания! Это удобно, если, например, Вы слушаете микс из отдельных дорожек.**

**Если Вам понравился трек, то не забудьте поставить ему _Like_ (кнопочка _Liked_ под строкой комментариев). Если трек Вам понравился настолько, что Вы готовы слушать его снова и снова, а также поделиться своей находкой с другими слушателями, то обязательно сделайте репост трека в своем профиле (кнопочка _Reposted_). Таким образом, песня сохраняется в Вашем профиле и ее могут слушать Ваши подписчики!**

**![](https://cdn-irec.r-99.com/sites/default/files/imagecache/copyright/user-images/143725/wEdbcDmw9itYs8wQIDvPg.jpg)**

**Также Вы можете создать микс из разных дорожек. Например, хотите собрать треки одного исполнителя, чтобы они звучали подряд. Тогда следует нажать кнопку _Добавить в плейлист_ - можно создать новый плейлист или добавить трек в уже созданный.**

![](https://cdn-irec.r-99.com/sites/default/files/imagecache/copyright/user-images/143725/xRjbdkSCOcLEeVRo1k6cg.jpg)

**По поводу скачивания треков.** _Скажу сразу, не все треки с Soundcloud доступны для скачивания. Дело в том, что на ресурсе собрана исключительно лицензионная музыка хорошего качества! Некоторые исполнители или ди-джеи, которые заливают свои творения на ресурс, предоставляют кнопки для бесплатного скачивания. Ну а некоторые товарищи лишь дают ссылку на платный раздел, откуда можно взять трек. Но даже если кнопки для скачивания нет, то в комментариях к треку можно просто попросить товарища, залившего трек, дать ссылку - на сайте хорошо работает обратная связь через комментарии!_

![](https://cdn-irec.r-99.com/sites/default/files/imagecache/copyright/user-images/143725/4rAjUFNleM54QpVCNZGQIA.jpg)

_**Таким образом, в Вашем профиле собираются Ваши любимые треки и плейлисты! Если кто-то из слушателей попадет на Ваш профиль и Ваши музыкальные вкусы совпадут, то он сможет подписаться на Вас (как на Айреке, примерно та же система). Но тут, Слава Небесам, с Вас взаимной подписки никто конючить не будет, это дело добровольное! )))**_

_**Приятно бывает, что среди подписчиков встречаются пользователи из самых разных уголков земного шара - Великобритания, США, Египет, Германия, Польша, Африка... Просто стираются все границы! )))**_

_**Благодаря SOUNDCLOUD, я расширила свои музыкальные горизонты. В моей жизни, помимо рок-музыки, появилось много других, самых разных направлений! При этом музыка не заезженная, здесь постят свои творения не только популярные музыканты, но и любители, желающие заявить о себе!**_

**_Если Вас заинтересовал этот ресурс, то скачивайте, слушайте и наслаждайтесь! Желаю приятного прослушивания!_**

Достоинства

*   Большой выбор музыки и направлений
*   Всё очень легко и удобно
*   Есть поиск по тэгам
*   Музыка хорошего качества

[La\_Muchacha](/users/lamuchacha "Информация о пользователе.") рекомендует

[сообщить о нарушении](#)

**Comment by TorturedDude** [comment]
**Данный отзыв был добавлен после описание такого сервиса, как soundcloud**

**Comment by wldmr-key** [comment]
все супер, но, увы, в таком виде этого слишком много для включения в пояснительную записку (разве что, как приложения). Я бы советовал обобщить прочитанные тобой отзывы и выделить основные моменты, которые нравятся/не нравятся пользователям. И, да, сделать выводы
