### ISSUE TITLE
Создать концептуальную схему данных предметной области

### ISSUE THREAD

**Issue by TorturedDude** [TorturedDude/KWMusicPleer#5]

**Comment by TorturedDude** [comment]
![This is an image](https://github.com/TorturedDude/KWMusicPleer/blob/main/Снимок%20экрана%202022-10-10%20в%2002.30.48.png?raw=true)

**Comment by wldmr-key** [comment]
нет-нет. Не может быть таких атрибутов, как список. А какие роли бывают? В описании предметой области ничего про них нет. А где тут подписки? И куда делась половина атрибутов из описания предметной области? А личные фонотеки, скачивания?
