### ISSUE TITLE
Изготовить прототип или скетчи пользовательского интерфейса

### ISSUE THREAD

**Issue by TorturedDude** [TorturedDude/KWMusicPleer#6]

**Comment by TorturedDude** [comment]
![This is an image](https://github.com/TorturedDude/KWMusicPleer/blob/main/Снимок%20экрана%202022-10-10%20в%2002.39.50.png?raw=true)

**Comment by wldmr-key** [comment]
этим, ведь, все не ограничится? Меня интересует не макет, а работа с данными
