### ISSUE TITLE
РПЗ

### ISSUE THREAD

**Issue by TorturedDude** [TorturedDude/KWMusicPleer#8]

**Comment by TorturedDude** [comment]
залил на гит

**Comment by wldmr-key** [comment]
концептуальная схема не согласуется с логической и в ней не исправлены ошибки, отмеченные ранее
Концептуальная и логическая схема не соответствуют описанию
не описан алгоритм формирования чартов
нет исходных кодов

**Comment by TorturedDude** [comment]
Схемы исправлю, чарты создаются через панель администратора.
А по поводу исходных кодов, зачем их в рпз вставлять, если у нас курсовая по базам данных, а все запросы и креэйты таблиц уже есть в рпз

**Comment by TorturedDude** [comment]
По факту документация составляется для проекта, т.е. как им пользоваться и что было использовано для данного проекта(технологии), если рассматривать относительно баз данных, то опять же повторюсь все данные присутствуют

**Comment by wldmr-key** [comment]
то есть, чарты админ сам составляет?!!!
исходные коды должны быть в репозитории, а не в РПЗ

**Comment by TorturedDude** [comment]
Насчёт исходных кодов - понял, а по поводу чартов, админ смотрит на количество прослушиваний и создаёт

**Comment by wldmr-key** [comment]
автоматизация - супер!!!

**Comment by TorturedDude** [comment]
На будущее учту
